// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAutosCDK;

#nullable disable

namespace WebApiAutosCDK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220815145143_primera")]
    partial class primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiAutosCDK.Entidades.MarcaCDK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("MarcasCDK");
                });

            modelBuilder.Entity("WebApiAutosCDK.Entidades.ModeloCDK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MarcaCDKId")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaCDKId");

                    b.ToTable("ModelosCDK");
                });

            modelBuilder.Entity("WebApiAutosCDK.Entidades.ModeloCDK", b =>
                {
                    b.HasOne("WebApiAutosCDK.Entidades.MarcaCDK", "MarcaCDK")
                        .WithMany("ModelosCDK")
                        .HasForeignKey("MarcaCDKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarcaCDK");
                });

            modelBuilder.Entity("WebApiAutosCDK.Entidades.MarcaCDK", b =>
                {
                    b.Navigation("ModelosCDK");
                });
#pragma warning restore 612, 618
        }
    }
}
